import React from "react";

export class About extends React.Component {
    render() {
        return(
            <div id="about-page" className="page">
                <h1>O Nas</h1>
                <p>

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse id sem lacus. Nunc congue ultrices quam, id cursus magna semper non. Cras pharetra cursus nisl id consequat. Nulla eget semper elit. Duis ut blandit est, quis porttitor ante. Donec eu ligula et leo aliquam pellentesque. In ornare ornare neque. Praesent malesuada porttitor eros vel lacinia. Mauris sodales tellus at diam lacinia sagittis. Fusce venenatis massa id tellus tincidunt, vel egestas erat viverra. Nulla vitae varius nibh, pellentesque dapibus eros. Ut non elit in nisl faucibus consequat non sit amet ligula. Cras fringilla, ligula sit amet pellentesque porta, nunc justo maximus erat, vel dignissim velit urna sed libero. Nam nibh elit, sagittis ac erat et, finibus sodales risus. Cras maximus, mi et faucibus sodales, libero lectus bibendum est, ac lacinia tellus ipsum vitae lorem. Curabitur et nunc erat.
                    
                    Phasellus lorem ipsum, cursus vel diam sed, cursus euismod justo. Quisque accumsan accumsan sem, viverra luctus magna consequat id. Donec aliquet sodales lacus, et molestie leo rhoncus dictum. Vestibulum ut velit eget massa scelerisque bibendum sed sit amet dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque erat dolor, maximus ac tristique eget, lacinia et urna. Mauris feugiat sodales libero, quis pulvinar est viverra eget. Nullam quis fermentum massa, nec varius justo. Duis gravida risus vitae quam cursus, eu vulputate augue volutpat. Aenean blandit finibus viverra. Maecenas rhoncus ex quis risus consectetur, at rhoncus est viverra. Duis sit amet ante dui.
                    
                    Curabitur sem nunc, faucibus sit amet semper quis, posuere non est. Praesent accumsan ante id sem venenatis vehicula. Fusce bibendum vitae ante accumsan fringilla. In aliquet varius elit in gravida. Fusce tempus lacus quis purus faucibus, vel vestibulum arcu iaculis. Nullam at ullamcorper neque. Sed pulvinar erat purus. Integer dapibus ante sapien, vel convallis metus dignissim nec. Maecenas nec velit eget nibh molestie blandit. Duis posuere faucibus nulla sit amet hendrerit. Pellentesque commodo mollis lorem, sed scelerisque eros egestas nec. Donec eu erat non massa vulputate ultricies hendrerit a urna. Aliquam elementum neque at est blandit, quis euismod enim vehicula. Praesent sagittis ornare neque nec posuere. Donec in placerat tortor. Aenean et pharetra mauris.
                    
                    Aenean malesuada est id porttitor cursus. Quisque molestie, metus ut congue cursus, lectus sem ullamcorper urna, a molestie diam risus et metus. In in eros interdum, pulvinar sem id, viverra libero. Vestibulum congue fermentum tortor sed convallis. In hac habitasse platea dictumst. Curabitur pharetra, augue sed efficitur pretium, nunc quam sodales arcu, vel iaculis felis mauris a nunc. Nullam posuere dui tortor, eu posuere felis fringilla sit amet. Vestibulum dapibus ligula purus, eu iaculis nunc consectetur vel. Donec nulla quam, lacinia sit amet fringilla at, faucibus a lectus. Aenean sodales neque in sollicitudin malesuada. Pellentesque ultricies ipsum metus, eget feugiat sapien sollicitudin vel. Ut eget metus at elit sodales venenatis. Donec quis porta dolor.
                    
                    Sed mattis, odio rhoncus ullamcorper sodales, diam erat maximus mauris, ultricies ornare lorem eros vitae metus. Sed ultrices, urna vitae luctus elementum, enim elit rhoncus elit, et pellentesque eros lacus vitae ex. Mauris ut lectus in quam luctus mattis. Integer tempus felis lacus, nec commodo lectus imperdiet vel. Nulla in mollis lectus. Quisque est neque, placerat sed eros ac, semper ornare nisl. Curabitur posuere nulla nisi, eu imperdiet quam placerat et. Aenean a lobortis nisi.
                    
                    Nam vitae sagittis lacus. Maecenas rutrum eget ligula quis tristique. Proin blandit sapien ac diam interdum bibendum. Cras laoreet sed purus vulputate consectetur. In porttitor tincidunt erat eget ullamcorper. Ut dui tortor, finibus vitae rutrum a, tincidunt et sapien. Duis elit libero, molestie at nulla vel, suscipit luctus metus. Vivamus massa arcu, iaculis egestas ante consectetur, fringilla aliquam metus. Phasellus metus eros, ultrices eu ligula eget, congue cursus tortor. Cras nec turpis ipsum.
                    
                    Phasellus efficitur luctus vestibulum. Cras mattis elit et enim imperdiet convallis. Maecenas ut egestas nisi. Donec at erat diam. Donec mattis rhoncus diam, vitae pharetra arcu aliquam nec. Donec tincidunt blandit lectus, at gravida nunc ultrices eu. Quisque blandit congue nulla eget porttitor. Suspendisse ultricies erat a egestas lacinia. Pellentesque malesuada euismod justo lobortis hendrerit. Curabitur ultrices lacus purus, vel vestibulum mi tempus in. Suspendisse elementum ullamcorper magna sit amet vehicula. In hac habitasse platea dictumst.
                    
                    In a urna nec urna feugiat posuere. Curabitur nec quam consectetur, tincidunt nunc nec, pharetra lacus. Ut non lorem consequat, congue nisi sit amet, porttitor erat. Quisque auctor felis enim. Cras et felis euismod, molestie neque at, posuere lacus. Mauris a velit vitae libero vulputate accumsan. Quisque eu vehicula sapien. Cras justo justo, fermentum a nisi id, condimentum hendrerit enim. Integer a varius mi. Phasellus sem nulla, euismod rutrum quam id, cursus varius lectus. Suspendisse malesuada diam id libero iaculis, non ornare turpis feugiat. Morbi in libero ullamcorper, finibus eros sit amet, porta sem. Cras lacinia ipsum sapien, sit amet vestibulum lectus rhoncus sed. Sed facilisis metus a ultrices lacinia. Ut a enim in ligula congue tempus.
                    
                    Nunc aliquam semper libero. Maecenas pulvinar aliquam lectus. Donec eget magna elementum, tempor velit id, finibus nibh. Curabitur nibh dui, condimentum id finibus sit amet, imperdiet non erat. Donec rhoncus malesuada felis in eleifend. Sed facilisis nibh in orci sollicitudin, ac tempor libero tincidunt. Aenean id est a magna imperdiet semper.
                    
                    Donec a rhoncus metus. Integer lacinia neque enim, sed venenatis est molestie et. Aenean felis augue, finibus sed accumsan nec, dignissim eget magna. Proin sem leo, pellentesque vel fringilla id, ultrices ac nisl. Vestibulum vehicula arcu sem, a vestibulum mi fermentum rutrum. Nunc quis faucibus risus. Sed lectus enim, pellentesque quis odio ac, vestibulum ornare arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas nec tincidunt nibh. Proin augue tellus, viverra a ipsum a, iaculis consectetur quam.
                    
                    Sed blandit imperdiet bibendum. Nullam ac posuere odio. Sed vel odio aliquam, interdum felis ut, fermentum nunc. Aliquam lacus lacus, bibendum in ultricies vitae, ullamcorper in turpis. Curabitur rutrum dui libero, non vulputate libero egestas nec. Mauris finibus efficitur tellus, non iaculis urna scelerisque at. Sed enim eros, ultricies non diam ac, molestie aliquet augue. Nullam vitae elit id lectus gravida feugiat elementum nec justo. Maecenas dictum, odio finibus rhoncus euismod, quam ligula vestibulum libero, sit amet posuere felis nibh sit amet mi. Nullam vel porttitor leo, at mattis arcu. In eget risus dictum, sagittis magna eu, mollis ipsum. Donec sed velit nec lectus malesuada pharetra.
                    
                    Phasellus ultrices id lectus sit amet porta. Fusce vel sodales massa, et sollicitudin massa. Ut feugiat, lorem in feugiat fermentum, sem urna condimentum diam, ac varius erat elit at lacus. Sed varius velit maximus sem aliquam maximus. Nullam suscipit nulla eget lacinia rhoncus. Pellentesque aliquam, ex nec elementum consectetur, dui lacus egestas odio, at feugiat quam nisi at mi. Donec condimentum nisi urna, ac bibendum massa ultricies eget. Suspendisse in malesuada felis. Sed sit amet lacus risus. Ut vitae tristique lacus, nec aliquam ante. Suspendisse odio ipsum, ullamcorper nec faucibus id, ornare non risus. Nullam tempor nunc dignissim accumsan facilisis.
                    
                    Praesent maximus neque justo, id semper ipsum sollicitudin a. Cras sollicitudin lectus sit amet sapien maximus euismod. Integer semper pellentesque facilisis. Donec dui est, efficitur eu nulla vitae, lobortis consectetur lacus. Donec cursus neque justo, sed aliquam est tincidunt dignissim. Maecenas rhoncus diam sed sollicitudin finibus. Vivamus lobortis rhoncus neque sed venenatis. Nam dolor massa, feugiat id ullamcorper et, finibus ac mauris. Donec scelerisque lacus nec erat vehicula suscipit. Phasellus pharetra magna et mauris lacinia, non cursus leo laoreet. Ut sollicitudin dictum volutpat. Morbi ac scelerisque purus.
                    
                    Curabitur in erat ac leo tempor blandit. Etiam dignissim leo non nulla sodales imperdiet et eget massa. Praesent vitae velit tellus. Nulla finibus urna ut tristique vestibulum. Nam euismod, sapien sit amet pellentesque efficitur, ex tortor tempor lacus, vitae lacinia mauris leo vel neque. Integer imperdiet feugiat faucibus. Curabitur pretium urna et arcu dapibus fringilla. Maecenas sed tincidunt purus. Pellentesque turpis leo, dapibus id suscipit id, pretium eu nisi. Nunc feugiat leo non leo suscipit placerat. Phasellus ut nisl eget ipsum molestie consequat.
                    
                    Praesent vitae nisi vel mi feugiat sodales rutrum et massa. Morbi finibus porttitor velit, eu viverra ex. Suspendisse efficitur lacus viverra odio laoreet, a tempor magna mollis. Duis sollicitudin quam ut vehicula sodales. Sed egestas ornare velit malesuada porta. Aenean ac tincidunt mi, eget aliquam metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed aliquet mollis luctus. Integer vel auctor erat, et dignissim dolor. In est massa, fringilla eget consequat quis, placerat congue felis.
                    
                    Suspendisse diam turpis, tristique quis porta at, posuere id ligula. Quisque tempor lacus vel tortor eleifend, sollicitudin viverra ante bibendum. Nam lobortis nisi vel tincidunt bibendum. Aliquam metus ipsum, pellentesque et condimentum ut, fermentum non risus. Aliquam eget ante metus. Morbi enim nisi, faucibus non tempus non, ullamcorper quis ipsum. Aliquam placerat pharetra imperdiet. Aenean ac luctus turpis. Curabitur nulla neque, semper at elit sed, tempor iaculis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam malesuada semper justo a rhoncus. Proin tempus libero sapien, id feugiat neque mattis dictum. Sed elit ipsum, suscipit at sagittis eget, mollis et augue. Morbi ut eleifend mi, non vulputate est.
                    
                    Nullam et nisl sit amet nibh dictum dictum vel id enim. Pellentesque nibh nulla, consequat eu purus et, placerat cursus tortor. Phasellus ultricies id sem eu tristique. Praesent vitae nunc purus. Praesent laoreet lacus ullamcorper nulla fringilla tristique. Pellentesque scelerisque justo ut augue convallis, eu rhoncus magna pulvinar. Maecenas aliquam porta tristique. Curabitur ut sodales massa, in aliquet est. Aliquam non rutrum ex. Donec eget lorem nec magna bibendum sodales. Nunc placerat nunc et ipsum accumsan, vel iaculis lorem ornare. Vivamus non eleifend tortor.
                    
                    Integer eget metus id purus posuere lobortis sed vel magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi vitae pulvinar metus. Aliquam erat volutpat. Aenean aliquet ultricies massa, sodales varius magna tristique at. Phasellus eu leo scelerisque, aliquet arcu et, posuere urna. In hac habitasse platea dictumst.
                    
                    Nunc eu tortor dignissim, fermentum urna nec, malesuada eros. Nullam condimentum magna ipsum, in sollicitudin lorem fringilla dictum. Vestibulum mollis nisl in urna ornare, ac rutrum dolor scelerisque. Quisque placerat ullamcorper eros eu luctus. Curabitur sed tellus non sem pretium luctus. Donec ac mauris quam. Sed consectetur at enim quis feugiat.
                    
In laoreet magna eu justo mattis tincidunt id ornare eros. Maecenas vehicula justo nec feugiat porttitor. Nunc vulputate urna et tortor ultricies, at iaculis magna convallis. Mauris et enim eget purus vehicula ultricies in id nulla. Mauris et nibh non eros sodales maximus eget sit amet nisl. Mauris maximus faucibus ex ac bibendum. Duis vel venenatis lacus. Praesent volutpat libero tincidunt mollis fermentum. Aliquam efficitur vitae velit eget euismod. Integer venenatis lectus orci, ut rhoncus mi tempus efficitur. Pellentesque ullamcorper congue mauris at porta. Etiam arcu elit, egestas sed sollicitudin non, pretium a massa. </p>
            </div>
        )
    }
}